In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('avocado.csv')
df.head()

Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0           0  2015-12-27          1.33      64236.62  1036.74   54454.85   
1           1  2015-12-20          1.35      54876.98   674.28   44638.81   
2           2  2015-12-13          0.93     118220.22   794.70  109149.67   
3           3  2015-12-06          1.08      78992.15  1132.00   71976.41   
4           4  2015-11-29          1.28      51039.60   941.48   43838.39   

     4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0   48.16     8696.87     8603.62       93.25          0.0  conventional   
1   58.33     9505.56     9408.07       97.49          0.0  conventional   
2  130.50     8145.35     8042.21      103.14          0.0  conventional   
3   72.58     5811.16     5677.40      133.76          0.0  conventional   
4   75.78     6183.95     5986.26      197.69          0.0  conventional   

   year  region  
0  2015  Albany  
1  2015  Albany  
2  2015  Albany  
3  2015  Albany  
4  2015  Albany

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18249 entries, 0 to 18248
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    18249 non-null  int64  
 1   Date          18249 non-null  object 
 2   AveragePrice  18249 non-null  float64
 3   Total Volume  18249 non-null  float64
 4   4046          18249 non-null  float64
 5   4225          18249 non-null  float64
 6   4770          18249 non-null  float64
 7   Total Bags    18249 non-null  float64
 8   Small Bags    18249 non-null  float64
 9   Large Bags    18249 non-null  float64
 10  XLarge Bags   18249 non-null  float64
 11  type          18249 non-null  object 
 12  year          18249 non-null  int64  
 13  region        18249 non-null  object 
dtypes: float64(9), int64(2), object(3)
memory usage: 1.9+ MB


In [4]:
df.isnull().sum()

Unnamed: 0      0
Date            0
AveragePrice    0
Total Volume    0
4046            0
4225            0
4770            0
Total Bags      0
Small Bags      0
Large Bags      0
XLarge Bags     0
type            0
year            0
region          0
dtype: int64

In [5]:
df.describe()

Unnamed: 0  AveragePrice  Total Volume          4046          4225  \
count  18249.000000  18249.000000  1.824900e+04  1.824900e+04  1.824900e+04   
mean      24.232232      1.405978  8.506440e+05  2.930084e+05  2.951546e+05   
std       15.481045      0.402677  3.453545e+06  1.264989e+06  1.204120e+06   
min        0.000000      0.440000  8.456000e+01  0.000000e+00  0.000000e+00   
25%       10.000000      1.100000  1.083858e+04  8.540700e+02  3.008780e+03   
50%       24.000000      1.370000  1.073768e+05  8.645300e+03  2.906102e+04   
75%       38.000000      1.660000  4.329623e+05  1.110202e+05  1.502069e+05   
max       52.000000      3.250000  6.250565e+07  2.274362e+07  2.047057e+07   

               4770    Total Bags    Small Bags    Large Bags    XLarge Bags  \
count  1.824900e+04  1.824900e+04  1.824900e+04  1.824900e+04   18249.000000   
mean   2.283974e+04  2.396392e+05  1.821947e+05  5.433809e+04    3106.426507   
std    1.074641e+05  9.862424e+05  7.461785e+05  2.439660e+05   17692.894652   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00       0.000000   
25%    0.000000e+00  5.088640e+03  2.849420e+03  1.274700e+02       0.000000   
50%    1.849900e+02  3.974383e+04  2.636282e+04  2.647710e+03       0.000000   
75%    6.243420e+03  1.107834e+05  8.333767e+04  2.202925e+04     132.500000   
max    2.546439e+06  1.937313e+07  1.338459e+07  5.719097e+06  551693.650000   

               year  
count  18249.000000  
mean    2016.147899  
std        0.939938  
min     2015.000000  
25%     2015.000000  
50%     2016.000000  
75%     2017.000000  
max     2018.000000

In [6]:
df['type'].unique()

array(['conventional', 'organic'], dtype=object)

In [7]:
df['region'].unique()

array(['Albany', 'Atlanta', 'BaltimoreWashington', 'Boise', 'Boston',
       'BuffaloRochester', 'California', 'Charlotte', 'Chicago',
       'CincinnatiDayton', 'Columbus', 'DallasFtWorth', 'Denver',
       'Detroit', 'GrandRapids', 'GreatLakes', 'HarrisburgScranton',
       'HartfordSpringfield', 'Houston', 'Indianapolis', 'Jacksonville',
       'LasVegas', 'LosAngeles', 'Louisville', 'MiamiFtLauderdale',
       'Midsouth', 'Nashville', 'NewOrleansMobile', 'NewYork',
       'Northeast', 'NorthernNewEngland', 'Orlando', 'Philadelphia',
       'PhoenixTucson', 'Pittsburgh', 'Plains', 'Portland',
       'RaleighGreensboro', 'RichmondNorfolk', 'Roanoke', 'Sacramento',
       'SanDiego', 'SanFrancisco', 'Seattle', 'SouthCarolina',
       'SouthCentral', 'Southeast', 'Spokane', 'StLouis', 'Syracuse',
       'Tampa', 'TotalUS', 'West', 'WestTexNewMexico'], dtype=object)

In [8]:
df['year'].unique()

array([2015, 2016, 2017, 2018])

In [ ]:
diag=sns.pairplot(df,kind='reg')

In [ ]:
date_ordering=sorted(df['Date'].unique())

In [ ]:
pd.get_dummies(df['region'])

In [ ]:
def ordinal_encode(df,column,ordering):
    df=df.copy()
    df[column]=df[column].apply(lambda x:ordering.index(x))
    return df

In [ ]:
def onehot_encode(df,column):
    df=df.copy()
    dummies=pd.get_dummies(df[column])
    df=pd.concat([df,dummies],axis=1)
    df.drop(column, axis=1, inplace=True)
    return df

In [ ]:
df=ordinal_encode(df,'Date',date_ordering)

In [ ]:
df=onehot_encode(df,'region')

In [ ]:
df

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
df['type']=label_encoder.fit_transform(df['type'])

In [ ]:
df

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop('AveragePrice',axis=1)
y=df['AveragePrice']

In [ ]:
y

In [ ]:
scaler=StandardScaler()
x=scaler.fit_transform(x)

In [ ]:
x.shape

In [ ]:
y.shape

In [4]:
from sklearn.model_selection import cross_val_score
def regression(model,x,y):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=10)
    model.fit(x_train,y_train)
    print('Accuracy :', model.score(x_test,y_test)*100)
    score=cross_val_score(model,x,y,cv=8)
    print("CV Score", np.mean(score)*100)

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
regression(model,x,y)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
regression(model,x,y)

# For Classification

In [14]:
dflr=pd.read_csv('avocado.csv')
dflr

Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0               0  2015-12-27          1.33      64236.62  1036.74   54454.85   
1               1  2015-12-20          1.35      54876.98   674.28   44638.81   
2               2  2015-12-13          0.93     118220.22   794.70  109149.67   
3               3  2015-12-06          1.08      78992.15  1132.00   71976.41   
4               4  2015-11-29          1.28      51039.60   941.48   43838.39   
...           ...         ...           ...           ...      ...        ...   
18244           7  2018-02-04          1.63      17074.83  2046.96    1529.20   
18245           8  2018-01-28          1.71      13888.04  1191.70    3431.50   
18246           9  2018-01-21          1.87      13766.76  1191.92    2452.79   
18247          10  2018-01-14          1.93      16205.22  1527.63    2981.04   
18248          11  2018-01-07          1.62      17489.58  2894.77    2356.13   

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional   
1       58.33     9505.56     9408.07       97.49          0.0  conventional   
2      130.50     8145.35     8042.21      103.14          0.0  conventional   
3       72.58     5811.16     5677.40      133.76          0.0  conventional   
4       75.78     6183.95     5986.26      197.69          0.0  conventional   
...       ...         ...         ...         ...          ...           ...   
18244    0.00    13498.67    13066.82      431.85          0.0       organic   
18245    0.00     9264.84     8940.04      324.80          0.0       organic   
18246  727.94     9394.11     9351.80       42.31          0.0       organic   
18247  727.01    10969.54    10919.54       50.00          0.0       organic   
18248  224.53    12014.15    11988.14       26.01          0.0       organic   

       year            region  
0      2015            Albany  
1      2015            Albany  
2      2015            Albany  
3      2015            Albany  
4      2015            Albany  
...     ...               ...  
18244  2018  WestTexNewMexico  
18245  2018  WestTexNewMexico  
18246  2018  WestTexNewMexico  
18247  2018  WestTexNewMexico  
18248  2018  WestTexNewMexico  

[18249 rows x 14 columns]

In [15]:
date_order=sorted(dflr['Date'].unique())

In [16]:
def ordinal_encode(dflr,column,order):
    dflr=dflr.copy()
    dflr[column]=dflr[column].apply(lambda x:order.index(x))
    return dflr

In [19]:
dflr=ordinal_encode(dflr,'Date',date_order)

In [20]:
dflr

Unnamed: 0  Date  AveragePrice  Total Volume     4046       4225  \
0               0    51          1.33      64236.62  1036.74   54454.85   
1               1    50          1.35      54876.98   674.28   44638.81   
2               2    49          0.93     118220.22   794.70  109149.67   
3               3    48          1.08      78992.15  1132.00   71976.41   
4               4    47          1.28      51039.60   941.48   43838.39   
...           ...   ...           ...           ...      ...        ...   
18244           7   161          1.63      17074.83  2046.96    1529.20   
18245           8   160          1.71      13888.04  1191.70    3431.50   
18246           9   159          1.87      13766.76  1191.92    2452.79   
18247          10   158          1.93      16205.22  1527.63    2981.04   
18248          11   157          1.62      17489.58  2894.77    2356.13   

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional   
1       58.33     9505.56     9408.07       97.49          0.0  conventional   
2      130.50     8145.35     8042.21      103.14          0.0  conventional   
3       72.58     5811.16     5677.40      133.76          0.0  conventional   
4       75.78     6183.95     5986.26      197.69          0.0  conventional   
...       ...         ...         ...         ...          ...           ...   
18244    0.00    13498.67    13066.82      431.85          0.0       organic   
18245    0.00     9264.84     8940.04      324.80          0.0       organic   
18246  727.94     9394.11     9351.80       42.31          0.0       organic   
18247  727.01    10969.54    10919.54       50.00          0.0       organic   
18248  224.53    12014.15    11988.14       26.01          0.0       organic   

       year            region  
0      2015            Albany  
1      2015            Albany  
2      2015            Albany  
3      2015            Albany  
4      2015            Albany  
...     ...               ...  
18244  2018  WestTexNewMexico  
18245  2018  WestTexNewMexico  
18246  2018  WestTexNewMexico  
18247  2018  WestTexNewMexico  
18248  2018  WestTexNewMexico  

[18249 rows x 14 columns]

In [21]:
type=pd.get_dummies(dflr['type'],drop_first=True)
type

organic
0            0
1            0
2            0
3            0
4            0
...        ...
18244        1
18245        1
18246        1
18247        1
18248        1

[18249 rows x 1 columns]

In [22]:
dflr.drop(['type'],axis=1,inplace=True)
dflr.head()

Unnamed: 0  Date  AveragePrice  Total Volume     4046       4225    4770  \
0           0    51          1.33      64236.62  1036.74   54454.85   48.16   
1           1    50          1.35      54876.98   674.28   44638.81   58.33   
2           2    49          0.93     118220.22   794.70  109149.67  130.50   
3           3    48          1.08      78992.15  1132.00   71976.41   72.58   
4           4    47          1.28      51039.60   941.48   43838.39   75.78   

   Total Bags  Small Bags  Large Bags  XLarge Bags  year  region  
0     8696.87     8603.62       93.25          0.0  2015  Albany  
1     9505.56     9408.07       97.49          0.0  2015  Albany  
2     8145.35     8042.21      103.14          0.0  2015  Albany  
3     5811.16     5677.40      133.76          0.0  2015  Albany  
4     6183.95     5986.26      197.69          0.0  2015  Albany

In [23]:
dflr=pd.concat([dflr,type],axis=1)
dflr.head()

Unnamed: 0  Date  AveragePrice  Total Volume     4046       4225    4770  \
0           0    51          1.33      64236.62  1036.74   54454.85   48.16   
1           1    50          1.35      54876.98   674.28   44638.81   58.33   
2           2    49          0.93     118220.22   794.70  109149.67  130.50   
3           3    48          1.08      78992.15  1132.00   71976.41   72.58   
4           4    47          1.28      51039.60   941.48   43838.39   75.78   

   Total Bags  Small Bags  Large Bags  XLarge Bags  year  region  organic  
0     8696.87     8603.62       93.25          0.0  2015  Albany        0  
1     9505.56     9408.07       97.49          0.0  2015  Albany        0  
2     8145.35     8042.21      103.14          0.0  2015  Albany        0  
3     5811.16     5677.40      133.76          0.0  2015  Albany        0  
4     6183.95     5986.26      197.69          0.0  2015  Albany        0

In [26]:
dflr.drop('Unnamed: 0',axis=1)

Date  AveragePrice  Total Volume     4046       4225    4770  \
0        51          1.33      64236.62  1036.74   54454.85   48.16   
1        50          1.35      54876.98   674.28   44638.81   58.33   
2        49          0.93     118220.22   794.70  109149.67  130.50   
3        48          1.08      78992.15  1132.00   71976.41   72.58   
4        47          1.28      51039.60   941.48   43838.39   75.78   
...     ...           ...           ...      ...        ...     ...   
18244   161          1.63      17074.83  2046.96    1529.20    0.00   
18245   160          1.71      13888.04  1191.70    3431.50    0.00   
18246   159          1.87      13766.76  1191.92    2452.79  727.94   
18247   158          1.93      16205.22  1527.63    2981.04  727.01   
18248   157          1.62      17489.58  2894.77    2356.13  224.53   

       Total Bags  Small Bags  Large Bags  XLarge Bags  year  \
0         8696.87     8603.62       93.25          0.0  2015   
1         9505.56     9408.07       97.49          0.0  2015   
2         8145.35     8042.21      103.14          0.0  2015   
3         5811.16     5677.40      133.76          0.0  2015   
4         6183.95     5986.26      197.69          0.0  2015   
...           ...         ...         ...          ...   ...   
18244    13498.67    13066.82      431.85          0.0  2018   
18245     9264.84     8940.04      324.80          0.0  2018   
18246     9394.11     9351.80       42.31          0.0  2018   
18247    10969.54    10919.54       50.00          0.0  2018   
18248    12014.15    11988.14       26.01          0.0  2018   

                 region  organic  
0                Albany        0  
1                Albany        0  
2                Albany        0  
3                Albany        0  
4                Albany        0  
...                 ...      ...  
18244  WestTexNewMexico        1  
18245  WestTexNewMexico        1  
18246  WestTexNewMexico        1  
18247  WestTexNewMexico        1  
18248  WestTexNewMexico        1  

[18249 rows x 13 columns]

In [27]:
features=dflr.drop('region',axis=1)
target=dflr['region']

In [29]:
scaler=StandardScaler()
features=scaler.fit_transform(features)

In [30]:
features_train,features_test,target_train,target_test=train_test_split(features,target,test_size=0.20,random_state=42)

In [39]:
from sklearn.model_selection import cross_val_score

In [31]:
from sklearn.ensemble import RandomForestClassifier
f=RandomForestClassifier(n_estimators=20, criterion='entropy',random_state=42)
f.fit(features_train,target_train)

RandomForestClassifier(criterion='entropy', n_estimators=20, random_state=42)

In [33]:
from sklearn.metrics import confusion_matrix
m=confusion_matrix(target_test,f.predict(features_test))
TN=m[0][0]
TP=m[1][1]
FN=m[1][0]
FP=m[0][1]
print(m)
print('Accuracy = {}'.format((TP+TN)/(TP+TN+FP+FN)))

[[59  0  0 ...  0  0  0]
 [ 0 62  0 ...  0  0  0]
 [ 0  0 61 ...  0  0  0]
 ...
 [ 0  0  0 ... 67  0  0]
 [ 0  0  0 ...  0 64  0]
 [ 0  0  0 ...  0  0 52]]
Accuracy = 1.0


In [40]:
score=cross_val_score(f,features,target,cv=5)
print("CV Score of RandmForestClassifier :", np.mean(score)*100)

CV Score of RandmForestClassifier : 66.89589416503678


In [34]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression(max_iter=10000)
lg.fit(features_train,target_train)

LogisticRegression(max_iter=10000)

In [35]:
cm=confusion_matrix(target_test,lg.predict(features_test))
TN=cm[0][0]
TP=cm[1][1]
FN=cm[1][0]
FP=cm[0][1]
print(cm)
print('Accuracy = {}'.format((TP+TN)/(TP+TN+FP+FN)))

[[27  0  0 ...  0  0  0]
 [ 2 15  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 66  0  0]
 [ 0  0  0 ...  0 45  0]
 [ 1  0  0 ...  0  0 14]]
Accuracy = 0.9545454545454546


In [41]:
score=cross_val_score(lg,features,target,cv=5)
print("CV Score of LogisticRegression :", np.mean(score)*100)

CV Score of LogisticRegression : 27.435993347774012


In [36]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion='entropy')
dtc.fit(features_train,target_train)

DecisionTreeClassifier(criterion='entropy')

In [38]:
dcm=confusion_matrix(target_test,dtc.predict(features_test))
TN=dcm[0][0]
TP=dcm[1][1]
FN=dcm[1][0]
FP=dcm[0][1]
print(dcm)
print('Accuracy = {}'.format((TP+TN)/(TP+TN+FP+FN)))

[[52  0  0 ...  0  0  0]
 [ 0 47  0 ...  0  0  2]
 [ 0  0 54 ...  0  0  0]
 ...
 [ 0  0  0 ... 67  0  0]
 [ 0  0  0 ...  0 62  0]
 [ 0  0  0 ...  0  0 39]]
Accuracy = 1.0


In [42]:
score=cross_val_score(dtc,features,target,cv=5)
print("CV Score of DecisionTreeClassifier :", np.mean(score)*100)

CV Score of DecisionTreeClassifier : 54.829576127068016
