In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("salary.csv")
data

rank discipline  yrs.since.phd  yrs.service   sex  salary
0        Prof          B             19           18  Male  139750
1        Prof          B             20           16  Male  173200
2    AsstProf          B              4            3  Male   79750
3        Prof          B             45           39  Male  115000
4        Prof          B             40           41  Male  141500
..        ...        ...            ...          ...   ...     ...
392      Prof          A             33           30  Male  103106
393      Prof          A             31           19  Male  150564
394      Prof          A             42           25  Male  101738
395      Prof          A             25           15  Male   95329
396  AsstProf          A              8            4  Male   81035

[397 rows x 6 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   rank           397 non-null    object
 1   discipline     397 non-null    object
 2   yrs.since.phd  397 non-null    int64 
 3   yrs.service    397 non-null    int64 
 4   sex            397 non-null    object
 5   salary         397 non-null    int64 
dtypes: int64(3), object(3)
memory usage: 18.7+ KB


In [4]:
data.describe()

yrs.since.phd  yrs.service         salary
count     397.000000   397.000000     397.000000
mean       22.314861    17.614610  113706.458438
std        12.887003    13.006024   30289.038695
min         1.000000     0.000000   57800.000000
25%        12.000000     7.000000   91000.000000
50%        21.000000    16.000000  107300.000000
75%        32.000000    27.000000  134185.000000
max        56.000000    60.000000  231545.000000

In [5]:
data.isnull().sum()

rank             0
discipline       0
yrs.since.phd    0
yrs.service      0
sex              0
salary           0
dtype: int64

In [6]:
dataset=data.drop(["rank",'discipline','yrs.since.phd','sex'],axis=1)
dataset

yrs.service  salary
0             18  139750
1             16  173200
2              3   79750
3             39  115000
4             41  141500
..           ...     ...
392           30  103106
393           19  150564
394           25  101738
395           15   95329
396            4   81035

[397 rows x 2 columns]

In [7]:
x=dataset.iloc[:,:1].values
x

array([[18],
       [16],
       [ 3],
       [39],
       [41],
       [ 6],
       [23],
       [45],
       [20],
       [18],
       [ 8],
       [ 2],
       [ 1],
       [ 0],
       [18],
       [ 3],
       [20],
       [34],
       [23],
       [36],
       [26],
       [31],
       [30],
       [19],
       [ 8],
       [ 8],
       [23],
       [ 3],
       [ 0],
       [ 8],
       [ 4],
       [ 2],
       [ 9],
       [ 2],
       [ 2],
       [ 0],
       [21],
       [ 4],
       [31],
       [ 9],
       [ 2],
       [23],
       [27],
       [38],
       [19],
       [15],
       [28],
       [19],
       [25],
       [ 1],
       [28],
       [11],
       [ 3],
       [ 9],
       [11],
       [ 5],
       [21],
       [ 8],
       [ 9],
       [ 3],
       [ 8],
       [ 2],
       [31],
       [11],
       [ 3],
       [ 8],
       [12],
       [31],
       [17],
       [36],
       [ 2],
       [45],
       [19],
       [34],
       [23],
       [ 3],
       [ 3],

In [8]:
y=dataset.iloc[:,1:].values
y

array([[139750],
       [173200],
       [ 79750],
       [115000],
       [141500],
       [ 97000],
       [175000],
       [147765],
       [119250],
       [129000],
       [119800],
       [ 79800],
       [ 77700],
       [ 78000],
       [104800],
       [117150],
       [101000],
       [103450],
       [124750],
       [137000],
       [ 89565],
       [102580],
       [ 93904],
       [113068],
       [ 74830],
       [106294],
       [134885],
       [ 82379],
       [ 77000],
       [118223],
       [132261],
       [ 79916],
       [117256],
       [ 80225],
       [ 80225],
       [ 77000],
       [155750],
       [ 86373],
       [125196],
       [100938],
       [146500],
       [ 93418],
       [101299],
       [231545],
       [ 94384],
       [114778],
       [ 98193],
       [151768],
       [140096],
       [ 70768],
       [126621],
       [108875],
       [ 74692],
       [106639],
       [103760],
       [ 83900],
       [117704],
       [ 90215],
       [100135

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
x_train.shape

(317, 1)

In [12]:
x_test.shape


(80, 1)

In [13]:
y_train.shape

(317, 1)

In [14]:
y_test.shape

(80, 1)

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lg=LinearRegression()

In [17]:
lg.fit(x_train,y_train)

LinearRegression()

In [18]:
y_pred=lg.predict(x_test)

In [19]:
print(y_pred)

[[ 97624.92743638]
 [114217.78997568]
 [103155.88161615]
 [104999.5330094 ]
 [115139.61567231]
 [ 98546.75313301]
 [128967.00112173]
 [ 97624.92743638]
 [106843.18440266]
 [110530.48718917]
 [114217.78997568]
 [130810.65251499]
 [118826.91845883]
 [ 99468.57882963]
 [126201.52403185]
 [104999.5330094 ]
 [122514.22124534]
 [100390.40452626]
 [144638.03796441]
 [101312.23022289]
 [100390.40452626]
 [118826.91845883]
 [131732.47821162]
 [114217.78997568]
 [106843.18440266]
 [107765.01009929]
 [ 98546.75313301]
 [ 99468.57882963]
 [115139.61567231]
 [107765.01009929]
 [114217.78997568]
 [106843.18440266]
 [118826.91845883]
 [116983.26706557]
 [115139.61567231]
 [126201.52403185]
 [139107.08378464]
 [116061.44136894]
 [112374.13858243]
 [150168.99214418]
 [104999.5330094 ]
 [115139.61567231]
 [102234.05591952]
 [105921.35870603]
 [121592.39554871]
 [100390.40452626]
 [116061.44136894]
 [123436.04694197]
 [139107.08378464]
 [116061.44136894]
 [114217.78997568]
 [105921.35870603]
 [104077.707